#!/bin/bash
#
# This script install the ClassAdmin software.
#

if [[ $(whoami) != "root" ]];then
        echo -e "\033[1;31m[-]\033[0m You aren't root"
        exit
fi

function operation(){
	echo "========================================================================================="
	echo $1
	echo "========================================================================================="
	$2
}
echo -ne "Do you want install the ClassAdminS server or ClassAdmin client? [ClassAdmin/ClassAdminS]: "
read ask
if [[ $ask == "ClassAdmin" ]];then
        operation "Updating repositories." "apt-get update -y"
        operation "Installing packages." "apt-get install -y python3 python3-pip git zenity scrot"
        operation "Deleting Django/ and init.sql." "rm -rf ./Django && rm -f ./init.sql && rm -f ./services/ClassAdminS.socket && rm -f ./Daemon/ClassAdminS.service"
        operation "Installing pipreqs python3 library." "pip3 install pipreqs"
	operation "Getting python3 libraries necesary." "pipreqs ./"
	operation "Installing python3 libraries." "pip3 install -r ./requirements.txt"
	pip3 install pysmb 2> /dev/null
        operation "Adding environtment variables" $(sed -i '/CLASSADMIN/d' /etc/environment && echo 'CLASSADMIN_HOME=/etc/ClassAdmin' >> /etc/environment && echo 'CLASSADMIN_LOG=/var/log/ClassAdmin.log' >> /etc/environment && echo 'CLASSADMIN_SSL=/etc/ClassAdmin/ssl' >> /etc/environment && sed -i '/PYTHONPATH/d' /etc/environment && echo 'PYTHONPATH=/etc/ClassAdmin' >> /etc/environment)
        operation "Installing ClassAdmin CA Bundle" $(cp ./ssl/ClassAdmin.crt /usr/local/share/ca-certificates && update-ca-certificates)
        server=""
        while [[ $(echo $server | grep -E -o "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}") == "" ]];
        do
          echo -ne "\033[1;34m[?]\033[0m Which is ClassAdminS server IP address?: "
          read server
        done
        operation "Adding dns in /etc/hosts" $(sed -i '/classadmin.server/d' /etc/hosts && echo "$server     classadmin.server" >> /etc/hosts)
        operation "Installing ClasAdmin service" $(cp ./Daemon/ClassAdmin.service /lib/systemd/system && systemctl daemon-reload)
	notification=""
        while [[ $notification != "true" && $notification != "false" ]];
        do
          echo -ne "\033[1;34m[?]\033[0m Do you want that ClassAdmin service send system notifications? [true/false]: "
          read notification
        done
        operation "Configurating notifications" $(sed -i "s/\"notifications\": \"true\"/\"notifications\": \"$notification\"/g" ./services/ClassAdmin.conf)
        user=""
        while [[ $user == "" ]];
        do
          echo -ne "The notifications will be execute as user...: "
          read user
        done
        operation "Notifications will be execute as $user" $(sed -i "s/\"user\":\"whoami\"/\"user\":\"$user\"/g" ./services/ClassAdmin.conf)
        operation "Changing permissions for ClassAdmin proyect" $(chmod o+w /var/log)
        operation "Creating ClassAdmin user" $(useradd -p $(openssl passwd -6 12345678) -d /home/ClassAdmin -m -k --badname ClassAdmin)
        operation "Grantting permissons to X Server" $(echo 'if [ "$DISPLAY" != "" ]' >> /etc/profile && echo 'then' >> /etc/profile && echo "	xhost +si:localuser:root" >> /etc/profile && echo 'fi' >> /etc/profile && xhost +si:localuser:root)
        operation "Enabling ClassAdmin service in the boot" $(systemctl enable ClassAdmin)
        operation "Starting ClassAdmin service" $(systemctl start ClassAdmin)
	echo -e "\033[1;32m[+]\033[0m ClassAdmin installation completed"
else
        exit 1
fi